{{- if .Values.bitwarden_eso_provider.create_cluster_secret_store }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    webhook:
      url: {{ include "bitwarden-eso-provider.clusterSecretStore.loginUrl" . }}
      headers:
        Content-Type: application/json
      result:
        jsonPath: {{ include "bitwarden-eso-provider.clusterSecretStore.loginJsonPath" . }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  provider:
    webhook:
      url: {{ include "bitwarden-eso-provider.clusterSecretStore.fieldsUrl" . }}
      result:
        jsonPath: {{ include "bitwarden-eso-provider.clusterSecretStore.fieldsJsonPath" . }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-notes
spec:
  provider:
    webhook:
      url: {{ include "bitwarden-eso-provider.clusterSecretStore.notesUrl" . }}
      result:
        jsonPath: {{ include "bitwarden-eso-provider.clusterSecretStore.notesJsonPath" . }}
{{- end }}
