---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # this is the name of the ExternalSecret object
  name: cool-secret-4-dogs
  namespace: coolapp4dogs
spec:
  target:
    # This is the name of the secret in bitwarden
    name: cool-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # The kubernetes secret name
        password: |-
          {{ .password }}

  data:
    # the value to pass to the kubernetes secret.
    - secretKey: password
      sourceRef:
        storeRef:
          # Use the `bitwarden-login` store to get `username` and
          # `password` values from a bitwarden secret that does not
          # contain custom fields, Otherwise use `bitwarden-fields'
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        # This is the `name` of your bitwarden secret. 
        key: <your-secret-name>
        # This is the property of the bitwarden secret that we want
        property: <some-secret-property>
