name: Generate helm docs

on:
  pull_request:
    paths:
      - 'charts/bitwarden-eso-provider/Chart.yaml'
      - 'charts/bitwarden-eso-provider/values.yaml'

permissions:
  contents: write
  pull-requests: write
  deployments: read

jobs:
  update-docs:
    name: update-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render helm docs inside the README.md and push changes back to PR branch
        uses: jessebot/helm-docs-action@0.0.1
        with:
          working-dir: charts/bitwarden-eso-provider
          git-push: "true"
